# Spring Boot configuration
# TODO MVR we re-use the opennms database just to ensure we can read the opennms entities as well. Ideally this would be two datasources, but i didn't felt messing with it
spring.datasource.url=jdbc:postgresql://localhost:25432/opennms
spring.datasource.username=postgres
spring.datasource.password=VRL7FhR@mGw@djhS2A4

# activate temporarily
spring.jpa.hibernate.ddl-auto=none

# Bluebird internal configuration
org.bluebird.kafka.bootstrap-servers=localhost:9092
# TODO MVR maybe the properties should be named differently => use org.bluebird.integration.opennms.kafka.... .instead
org.bluebird.kafka.integration.opennms.enabled=true
org.bluebird.kafka.integration.opennms.groupId=onms-kafka-playground
org.bluebird.kafka.integration.opennms.topics.events=onms-hzn-events
org.bluebird.kafka.integration.opennms.topics.alarms=alarms
org.bluebird.kafka.integration.opennms.topics.nodes=nodes

org.bluebird.alarm.propagation.enabled=true