services:
  db:
    image: postgres:16
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: symbiont


