# Spring Boot configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bluebird
spring.datasource.username=postgres

# activate temporarily
# TODO MVR deactivate again
spring.jpa.hibernate.ddl-auto=create

# Bluebird internal configuration
org.bluebird.integration.opennms.home=${user.home}/dev/opennms/target/opennms-34.0.0-SNAPSHOT/
org.bluebird.kafka.bootstrap-servers=localhost:29092
# TODO MVR maybe the properties should be named differently => use org.bluebird.integration.opennms.kafka.... .instead
org.bluebird.kafka.integration.opennms.enabled=true
org.bluebird.kafka.integration.opennms.groupId=opennms
org.bluebird.kafka.integration.opennms.topics.events=events
org.bluebird.kafka.integration.opennms.topics.alarms=alarms
org.bluebird.kafka.integration.opennms.topics.nodes=nodes

org.bluebird.alarm.propagation.enabled=true