# Spring Boot configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/symbiont
spring.datasource.username=postgres

# activate temporarily
# TODO MVR deactivate again
spring.jpa.hibernate.ddl-auto=create

# Bluebird internal configuration
org.bluebird.kafka.bootstrap-servers=localhost:29092
org.bluebird.alarm.propagation.enabled=false